// src/pages/UnicornSuite.tsx — Unicorn Suite Dedicated Page with Live Script Generation
import { useState, useEffect } from 'react'
import { api } from '../api/client'
import { useJob } from '../hooks/useJob'
import {
  Card, KpiTile, LogTerminal, RunButton, StopButton, GhostBtn,
  Input, Select, Toggle, Badge
} from '../components/ui'

const PUR = '#A855F7', GRN = '#22C55E', RED = '#EF4444', G = '#F5A623', BLU = '#3B82F6', AMB = '#F59E0B'

const UNICORN_SCENARIOS = [
  { value: 'login_browse_checkout', label: 'Login → Browse → Checkout' },
  { value: 'search_filter_view', label: 'Search → Filter → View Detail' },
  { value: 'api_auth_crud', label: 'API Auth → CRUD Operations' },
  { value: 'homepage_nav_form', label: 'Homepage → Navigation → Form' },
]

export function UnicornSuite() {
  const uJob = useJob()
  const [uUrl, setUUrl] = useState('')
  const [uScen, setUScen] = useState('login_browse_checkout')
  const [uHdrs, setUHdrs] = useState('{\n  "Content-Type": "application/json"\n}')
  
  // Selected Load Test Tool
  const [selectedTool, setSelectedTool] = useState<'jmeter' | 'k6' | 'locust' | 'gatling'>('jmeter')

  // Tool specific configurations
  // JMeter
  const [jmThreads, setJmThreads] = useState('10')
  const [jmRampUp, setJmRampUp] = useState('60')
  const [jmLoops, setJmLoops] = useState('10')
  const [jmDuration, setJmDuration] = useState('5')
  const [jmMethod, setJmMethod] = useState('GET')
  const [jmAssertion, setJmAssertion] = useState('Status 200')
  const [jmListener, setJmListener] = useState('Summary Report')
  const [jmCsvFile, setJmCsvFile] = useState('users.csv')

  // k6
  const [k6Vus, setK6Vus] = useState('50')
  const [k6Duration, setK6Duration] = useState('30s')
  const [k6Stages, setK6Stages] = useState('5s:10, 10s:20, 5s:0')
  const [k6Thresholds, setK6Thresholds] = useState('http_req_duration < 500')
  const [k6Output, setK6Output] = useState('stdout')
  const [k6Scenario, setK6Scenario] = useState('login_browse_checkout')

  // Locust
  const [locUsers, setLocUsers] = useState('100')
  const [locSpawnRate, setLocSpawnRate] = useState('10')
  const [locRunTime, setLocRunTime] = useState('5m')
  const [locWaitMin, setLocWaitMin] = useState('500')
  const [locWaitMax, setLocWaitMax] = useState('1500')
  const [locTaskWeights, setLocTaskWeights] = useState('login:3, browse:5, checkout:2')
  const [locUserClass, setLocUserClass] = useState('HttpUser')
  const [locShape, setLocShape] = useState('Default')

  // Gatling
  const [gatUsers, setGatUsers] = useState('50')
  const [gatRampDuration, setGatRampDuration] = useState('10')
  const [gatInjection, setGatInjection] = useState('rampUsers')
  const [gatThrottle, setGatThrottle] = useState('100')
  const [gatFeeder, setGatFeeder] = useState('csv')
  const [gatCheckType, setGatCheckType] = useState('status.is(200)')

  const [copiedScript, setCopiedScript] = useState(false)
  const [copiedCmd, setCopiedCmd] = useState(false)

  const uRunning = uJob.state.status === 'running'
  const uResult = uJob.state.result

  // Parse custom headers cleanly for script inclusion
  let parsedHeaders: Record<string, string> = {}
  try {
    parsedHeaders = JSON.parse(uHdrs)
  } catch (e) {
    parsedHeaders = { "Content-Type": "application/json" }
  }

  // Generate scripts live based on configurations
  const getGeneratedScriptAndCmd = () => {
    let target = uUrl.trim()
    if (target && !/^https?:\/\//i.test(target)) {
      target = 'https://' + target
    }
    target = target || 'https://your-site.com'
    let host = target
    let path = '/'
    try {
      const urlObj = new URL(target)
      host = urlObj.origin
      path = urlObj.pathname + urlObj.search
    } catch (_) {}

    if (selectedTool === 'jmeter') {
      const headerNodes = Object.entries(parsedHeaders)
        .map(([k, v]) => `            <elementProp name="" elementType="Header">\n              <stringProp name="Header.name">${k}</stringProp>\n              <stringProp name="Header.value">${v}</stringProp>\n            </elementProp>`)
        .join('\n')

      const jmx = `<?xml version="1.0" encoding="UTF-8"?>
<jmeterTestPlan version="1.2" properties="5.0" jmeter="5.5">
  <hashTree>
    <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="Unicorn Suite Test Plan" enabled="true">
      <stringProp name="TestPlan.comments">Auto-generated by SiteSentinel Matrix Pro</stringProp>
      <boolProp name="TestPlan.functional_mode">false</boolProp>
      <boolProp name="TestPlan.tearDown_on_shutdown">true</boolProp>
      <serializeThreadGroups>false</serializeThreadGroups>
      <elementProp name="TestPlan.user_defined_variables" elementType="Arguments" guiclass="ArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
        <collectionProp name="Arguments.arguments"/>
      </elementProp>
      <stringProp name="TestPlan.user_define_classpath"></stringProp>
    </TestPlan>
    <hashTree>
      <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="Unicorn Threads" enabled="true">
        <stringProp name="ThreadGroup.on_sample_error">continue</stringProp>
        <elementProp name="ThreadGroup.main_controller" elementType="LoopController" guiclass="LoopControlPanel" testclass="LoopController" testname="Loop Controller" enabled="true">
          <boolProp name="LoopController.continue_forever">false</boolProp>
          <stringProp name="LoopController.loops">${jmLoops}</stringProp>
        </elementProp>
        <stringProp name="ThreadGroup.num_threads">${jmThreads}</stringProp>
        <stringProp name="ThreadGroup.ramp_time">${jmRampUp}</stringProp>
        <boolProp name="ThreadGroup.scheduler">true</boolProp>
        <stringProp name="ThreadGroup.duration">${Number(jmDuration) * 60}</stringProp>
        <stringProp name="ThreadGroup.delay"></stringProp>
        <boolProp name="ThreadGroup.same_user_on_next_iteration">true</boolProp>
      </ThreadGroup>
      <hashTree>
        <HeaderManager guiclass="HeaderPanel" testclass="HeaderManager" testname="HTTP Header Manager" enabled="true">
          <collectionProp name="HeaderManager.headers">
${headerNodes}
          </collectionProp>
        </HeaderManager>
        <hashTree/>
        <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="HTTP Request" enabled="true">
          <elementProp name="HTTPsampler.Arguments" elementType="Arguments" guiclass="HTTPArgumentsPanel" testclass="Arguments" enabled="true">
            <collectionProp name="Arguments.arguments"/>
          </elementProp>
          <stringProp name="HTTPSampler.domain">${host.replace(/^https?:\/\//, '')}</stringProp>
          <stringProp name="HTTPSampler.port"></stringProp>
          <stringProp name="HTTPSampler.protocol">${target.startsWith('https') ? 'https' : 'http'}</stringProp>
          <stringProp name="HTTPSampler.contentEncoding"></stringProp>
          <stringProp name="HTTPSampler.path">${path}</stringProp>
          <stringProp name="HTTPSampler.method">${jmMethod}</stringProp>
          <boolProp name="HTTPSampler.follow_redirects">true</boolProp>
          <boolProp name="HTTPSampler.auto_redirects">false</boolProp>
          <boolProp name="HTTPSampler.use_keepalive">true</boolProp>
          <boolProp name="HTTPSampler.DO_MULTIPART_POST">false</boolProp>
          <stringProp name="HTTPSampler.embedded_url_re"></stringProp>
          <stringProp name="HTTPSampler.connect_timeout"></stringProp>
          <stringProp name="HTTPSampler.response_timeout"></stringProp>
        </HTTPSamplerProxy>
        <hashTree>
          <ResponseAssertion guiclass="AssertionGui" testclass="ResponseAssertion" testname="Response Assertion" enabled="true">
            <collectionProp name="Asserion.test_strings">
              <stringProp name="49586">${jmAssertion.includes('200') ? '200' : '200'}</stringProp>
            </collectionProp>
            <stringProp name="Assertion.custom_message"></stringProp>
            <stringProp name="Assertion.test_field">Assertion.response_code</stringProp>
            <boolProp name="Assertion.assume_success">false</boolProp>
            <intProp name="Assertion.test_type">8</intProp>
          </ResponseAssertion>
          <hashTree/>
        </hashTree>
        ${jmCsvFile ? `<!-- CSV Feeder: ${jmCsvFile} config goes here -->` : ''}
      </hashTree>
    </hashTree>
  </hashTree>
</jmeterTestPlan>`

      const cmd = `jmeter -n -t testplan.jmx -l results.jtl -e -o report/`
      return { script: jmx, filename: 'testplan.jmx', cmd }
    } else if (selectedTool === 'k6') {
      const stagesStr = k6Stages.split(',').map(s => {
        const [d, t] = s.trim().split(':')
        return `    { duration: '${d || '5s'}', target: ${t || 0} }`
      }).join(',\n')

      const script = `import http from 'k6/http';
import { check, sleep } from 'k6';

export const options = {
  stages: [
${stagesStr}
  ],
  thresholds: {
    'http_req_duration': ['${k6Thresholds.replace('http_req_duration', '').trim() || 'p(95)<500'}'],
  },
};

export default function () {
  const url = '${target}';
  const params = {
    headers: ${JSON.stringify(parsedHeaders, null, 2).replace(/\n/g, '\n  ')},
  };

  // Scenario execution: ${k6Scenario}
  const res = http.request('GET', url, null, params);

  check(res, {
    'status is 200': (r) => r.status === 200,
  });

  sleep(1);
}`

      const cmd = `k6 run ${k6Output !== 'stdout' ? `--out ${k6Output}` : ''} script.js`
      return { script, filename: 'script.js', cmd }
    } else if (selectedTool === 'locust') {
      const headersPython = JSON.stringify(parsedHeaders, null, 4).replace(/\n/g, '\n        ')
      const taskWeightsList = locTaskWeights.split(',').map(t => {
        const [name, weight] = t.trim().split(':')
        return `    @task(${weight || 1})\n    def ${name || 'task'}_scenario(self):\n        self.client.request("${jmMethod || 'GET'}", "${path}", headers=self.headers)`
      }).join('\n\n')

      const script = `import time
from locust import HttpUser, task, between, constant

class UnicornUser(${locUserClass}):
    # Wait time between tasks (min to max wait time)
    wait_time = between(${Number(locWaitMin) / 1000}, ${Number(locWaitMax) / 1000})

    def on_start(self):
        self.headers = ${headersPython}

${taskWeightsList}

# Load shape configuration: ${locShape}
`
      const cmd = `locust -f locustfile.py --headless -u ${locUsers} -r ${locSpawnRate} --run-time ${locRunTime} --host=${host}`
      return { script, filename: 'locustfile.py', cmd }
    } else {
      // gatling
      const script = `package computerdatabase

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import scala.concurrent.duration._

class UnicornSimulation extends Simulation {

  val httpProtocol = http
    .baseUrl("${host}")
    .acceptHeader("application/json")
    .userAgentHeader("Mozilla/5.0 (Windows NT 10.0; Win64; x64) SiteSentinel")

  val scn = scenario("Unicorn QA Scenario")
    .exec(
      http("Scenario Execute")
        .request("${jmMethod || 'GET'}", "${path}")
        .check(${gatCheckType})
    )

  setUp(
    scn.inject(
      ${gatInjection === 'rampUsers' ? `rampUsers(${gatUsers}) during (${gatRampDuration} seconds)` : `atOnceUsers(${gatUsers})`}
    )
  ).protocols(httpProtocol)
    .throttle(reachRps(${gatThrottle}) in (10 seconds))
}
`
      const cmd = `mvn gatling:test -Dgatling.simulationClass=computerdatabase.UnicornSimulation`
      return { script, filename: 'UnicornSimulation.scala', cmd }
    }
  }

  const { script, filename, cmd } = getGeneratedScriptAndCmd()

  async function runUnicorn() {
    let t = uUrl.trim()
    if (t && !/^https?:\/\//i.test(t)) {
      t = 'https://' + t
      setUUrl(t)
    }
    let h: any = {}
    try {
      h = JSON.parse(uHdrs)
    } catch {
      h = {}
    }
    uJob.reset()
    const { job_id } = await api.unicorn({ url: t || 'https://your-site.com', scenario: uScen, headers: h, virtual_users: 5 })
    uJob.startJob(job_id)
  }

  const copyScript = () => {
    navigator.clipboard.writeText(script)
    setCopiedScript(true)
    setTimeout(() => setCopiedScript(false), 2000)
  }

  const copyCmd = () => {
    navigator.clipboard.writeText(cmd)
    setCopiedCmd(true)
    setTimeout(() => setCopiedCmd(false), 2000)
  }

  return (
    <div className="p-5 flex flex-col gap-4">
      {/* KPI Tiles */}
      <div className="flex gap-3">
        <KpiTile label="Steps" value={uResult?.steps?.length ?? 0} accent={PUR} />
        <KpiTile label="Passed" value={uResult?.passed ?? 0} accent={GRN} />
        <KpiTile label="Failed" value={uResult?.failed ?? 0} accent={RED} />
        <KpiTile label="Success Rate" value={uResult?.health ? uResult.health + '%' : '—'} accent={PUR} />
      </div>

      {/* Main split dashboard view */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
        
        {/* Left column: inputs */}
        <div className="flex flex-col gap-4">
          <Card title="Unicorn Execution Configuration" accent={PUR}>
            <div className="grid grid-cols-2 gap-3 mb-3">
              <Input label="Target URL" value={uUrl} onChange={setUUrl} placeholder="https://example.com" type="url" />
              <Select label="Test Scenario" value={uScen} onChange={setUScen} options={UNICORN_SCENARIOS} />
            </div>
            
            <div className="mb-3">
              <p className="font-display font-700 text-[10px] uppercase tracking-[0.07em] mb-1.5" style={{ color: '#484F58' }}>Custom Request Headers (JSON)</p>
              <textarea
                value={uHdrs}
                onChange={e => setUHdrs(e.target.value)}
                rows={3}
                className="be-input w-full resize-y font-mono"
                style={{ fontFamily: '"JetBrains Mono",monospace', fontSize: 11 }}
              />
            </div>

            <div className="flex items-center gap-3">
              <RunButton onClick={runUnicorn} disabled={uRunning} loading={uRunning} label={uRunning ? 'Running…' : '🦄 Run Unicorn Suite'} color={PUR} />
              <StopButton onClick={uJob.cancel} disabled={!uRunning} />
              <GhostBtn onClick={uJob.reset} label="Clear Log" />
            </div>
          </Card>

          {/* Config Widgets by Selected Tool */}
          <Card title="Load Tool Parameters" accent={PUR}>
            {/* Tool Selector Tab Bar */}
            <div className="flex bg-[#161B22] border border-[#30363D] rounded-xl p-1 mb-4">
              {(['jmeter', 'k6', 'locust', 'gatling'] as const).map(tool => (
                <button
                  key={tool}
                  onClick={() => setSelectedTool(tool)}
                  className="flex-1 py-2 font-display font-700 text-[11px] uppercase tracking-wider rounded-lg cursor-pointer transition-all"
                  style={{
                    background: selectedTool === tool ? PUR : 'transparent',
                    color: selectedTool === tool ? '#0A0A0A' : '#8B949E',
                    border: 'none'
                  }}
                >
                  {tool}
                </button>
              ))}
            </div>

            {/* JMeter parameters */}
            {selectedTool === 'jmeter' && (
              <div className="grid grid-cols-2 gap-4">
                <Input label="JMeter Threads" value={jmThreads} onChange={setJmThreads} type="number" />
                <Input label="Ramp-up (sec)" value={jmRampUp} onChange={setJmRampUp} type="number" />
                <Input label="Loop Count" value={jmLoops} onChange={setJmLoops} type="number" />
                <Input label="Duration (min)" value={jmDuration} onChange={setJmDuration} type="number" />
                <Select label="HTTP Method" value={jmMethod} onChange={setJmMethod} options={['GET', 'POST', 'PUT', 'PATCH', 'DELETE'].map(m => ({ value: m, label: m }))} />
                <Select label="Assertions" value={jmAssertion} onChange={setJmAssertion} options={['Status 200', 'Contains Success', 'P95 < 500ms', 'Custom'].map(a => ({ value: a, label: a }))} />
                <Select label="Listener" value={jmListener} onChange={setJmListener} options={['Summary Report', 'Aggregate Report', 'Graph Results'].map(l => ({ value: l, label: l }))} />
                <Input label="CSV Feeder File" value={jmCsvFile} onChange={setJmCsvFile} />
              </div>
            )}

            {/* k6 parameters */}
            {selectedTool === 'k6' && (
              <div className="grid grid-cols-2 gap-4">
                <Input label="Virtual Users (VUs)" value={k6Vus} onChange={setK6Vus} type="number" />
                <Input label="Duration" value={k6Duration} onChange={setK6Duration} />
                <Input label="Stages (Ramp-up profile)" value={k6Stages} onChange={setK6Stages} placeholder="5s:10, 10s:20, 5s:0" />
                <Input label="Thresholds" value={k6Thresholds} onChange={setK6Thresholds} placeholder="http_req_duration < 500" />
                <Input label="Output Destination" value={k6Output} onChange={setK6Output} />
                <Select label="Scenario" value={k6Scenario} onChange={setK6Scenario} options={UNICORN_SCENARIOS} />
              </div>
            )}

            {/* Locust parameters */}
            {selectedTool === 'locust' && (
              <div className="grid grid-cols-2 gap-4">
                <Input label="Users" value={locUsers} onChange={setLocUsers} type="number" />
                <Input label="Spawn Rate (users/s)" value={locSpawnRate} onChange={setLocSpawnRate} type="number" />
                <Input label="Run Time" value={locRunTime} onChange={setLocRunTime} />
                <div className="flex gap-2">
                  <Input label="Wait Min (ms)" value={locWaitMin} onChange={setLocWaitMin} type="number" className="flex-1" />
                  <Input label="Wait Max (ms)" value={locWaitMax} onChange={setLocWaitMax} type="number" className="flex-1" />
                </div>
                <Input label="Task Weights" value={locTaskWeights} onChange={setLocTaskWeights} />
                <Select label="User Class" value={locUserClass} onChange={setLocUserClass} options={[{ value: 'HttpUser', label: 'HttpUser' }, { value: 'FastHttpUser', label: 'FastHttpUser' }]} />
                <Select label="Load Shape" value={locShape} onChange={setLocShape} options={[{ value: 'Default', label: 'Default' }, { value: 'StagesShape', label: 'StagesShape' }]} />
              </div>
            )}

            {/* Gatling parameters */}
            {selectedTool === 'gatling' && (
              <div className="grid grid-cols-2 gap-4">
                <Input label="Concurrent Users" value={gatUsers} onChange={setGatUsers} type="number" />
                <Input label="Ramp Duration (sec)" value={gatRampDuration} onChange={setGatRampDuration} type="number" />
                <Select label="Injection Profile" value={gatInjection} onChange={setGatInjection} options={[{ value: 'rampUsers', label: 'Ramp Users' }, { value: 'atOnceUsers', label: 'At Once Users' }]} />
                <Input label="Throttle (RPS)" value={gatThrottle} onChange={setGatThrottle} type="number" />
                <Select label="Feeder Type" value={gatFeeder} onChange={setGatFeeder} options={[{ value: 'csv', label: 'CSV Feeder' }, { value: 'json', label: 'JSON Feeder' }]} />
                <Input label="Check Type" value={gatCheckType} onChange={setGatCheckType} />
              </div>
            )}
          </Card>
        </div>

        {/* Right column: Generated script panel */}
        <div className="flex flex-col gap-4">
          <Card
            title={`Auto-Generated ${selectedTool.toUpperCase()} Config Script`}
            accent={PUR}
            action={
              <button
                onClick={copyScript}
                className="px-3 py-1 text-[11px] font-display font-700 rounded-lg transition-all border border-[#30363D] cursor-pointer"
                style={{
                  background: copiedScript ? `${GRN}22` : '#161B22',
                  color: copiedScript ? GRN : '#8B949E',
                  borderColor: copiedScript ? GRN : '#30363D'
                }}
              >
                {copiedScript ? '✓ Copied' : '📋 Copy Script'}
              </button>
            }
          >
            <div className="flex items-center justify-between bg-[#161B22] px-4 py-2 border-b border-[#30363D] rounded-t-xl">
              <span className="font-mono text-[11px] text-[#8B949E]">{filename}</span>
            </div>
            <textarea
              readOnly
              value={script}
              rows={16}
              className="w-full bg-[#0D1117] border border-t-0 border-[#30363D] rounded-b-xl p-4 font-mono text-[11px] text-[#C9D1D9] resize-none focus:outline-none"
              style={{ fontFamily: '"JetBrains Mono",monospace' }}
            />
          </Card>

          <Card
            title="CLI Run Command"
            accent={PUR}
            action={
              <button
                onClick={copyCmd}
                className="px-3 py-1 text-[11px] font-display font-700 rounded-lg transition-all border border-[#30363D] cursor-pointer"
                style={{
                  background: copiedCmd ? `${GRN}22` : '#161B22',
                  color: copiedCmd ? GRN : '#8B949E',
                  borderColor: copiedCmd ? GRN : '#30363D'
                }}
              >
                {copiedCmd ? '✓ Copied' : '📋 Copy Command'}
              </button>
            }
          >
            <div className="bg-[#0D1117] border border-[#30363D] rounded-xl p-4 font-mono text-[12px] text-white flex items-center gap-2 overflow-x-auto whitespace-nowrap">
              <span className="text-[#888] select-none">$</span>
              <span>{cmd}</span>
            </div>
          </Card>
        </div>

      </div>

      {/* Live Output & Scenario steps table */}
      <LogTerminal logs={uJob.state.logs} height="h-44" accent={PUR} title="Unicorn Live Console Output" />

      {uResult && (
        <Card title="Scenario Step Verification results" accent={PUR}>
          <div className="overflow-x-auto rounded-xl border border-[#30363D] bg-[#0D1117]">
            <table className="w-full text-left border-collapse">
              <thead className="bg-[#161B22] border-b border-[#30363D]">
                <tr>
                  <th className="px-4 py-3 font-display font-700 text-[10px] uppercase tracking-widest text-[#484F58]">Step</th>
                  <th className="px-4 py-3 font-display font-700 text-[10px] uppercase tracking-widest text-[#484F58]">Method</th>
                  <th className="px-4 py-3 font-display font-700 text-[10px] uppercase tracking-widest text-[#484F58]">Status</th>
                  <th className="px-4 py-3 font-display font-700 text-[10px] uppercase tracking-widest text-[#484F58]">Response Time</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#1F242B]">
                {uResult.steps?.map((s: any, i: number) => (
                  <tr key={i} className="hover:bg-[#161B22] transition-colors">
                    <td className="px-4 py-3 font-display font-600 text-[12px] text-white">{s.step}</td>
                    <td className="px-4 py-3">
                      <span className="be-badge" style={{ color: PUR, background: 'rgba(168,85,247,0.1)', borderColor: 'rgba(168,85,247,0.3)', fontFamily: '"JetBrains Mono",monospace' }}>
                        {s.method}
                      </span>
                    </td>
                    <td className="px-4 py-3">
                      <span className="be-badge" style={{
                        color: s.ok ? GRN : RED,
                        background: s.ok ? 'rgba(34,197,94,0.1)' : 'rgba(239,68,68,0.1)',
                        borderColor: s.ok ? 'rgba(34,197,94,0.3)' : 'rgba(239,68,68,0.3)'
                      }}>
                        {s.status || 'ERR'} {s.ok ? '✓' : '✗'}
                      </span>
                    </td>
                    <td className="px-4 py-3 font-mono text-[11px] text-[#8B949E]">{s.ms}ms</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>
      )}

    </div>
  )
}
